In [1]:
import pandas as pd
import numpy as np

In [2]:
cols = ['user id', 'movie id', 'rating', 'timestamp']
r = pd.read_csv('../example data/ml-100k/u1.base', names = cols, sep='\t', encoding='latin-1')

In [3]:
r.head()

   user id  movie id  rating  timestamp
0        1         1       5  874965758
1        1         2       3  876893171
2        1         3       4  878542960
3        1         4       3  876893119
4        1         5       3  889751712

In [4]:
r.shape

(80000, 4)

In [5]:
print(len(r[r['rating'] == 1]))
print(len(r[r['rating'] == 2]))
print(len(r[r['rating'] == 3]))
print(len(r[r['rating'] == 4]))
print(len(r[r['rating'] == 5]))

4719
9178
21963
27396
16744

In [6]:
r['user id'].value_counts()

655    685
405    582
450    494
537    490
416    417
      ...
36       9
93       9
258      8
228      7
310      4
Name: user id, Length: 943, dtype: int64

In [7]:
len(r['user id'].value_counts())

943

In [8]:
ratings = pd.read_csv('../data/datasets/rating/cleaned_1_detail.csv', sep=',', encoding='latin-1')

In [9]:
ratings

,user id,movie id,rating,content,date
0,ur20552756,tt0102813,6.0,I am a big fan of animated movies and of anima...,22 June 2011
1,ur0391152,tt0102813,4.0,I've always had kind of a perverse curiosity a...,22 August 2010
2,ur34049683,tt0102813,5.0,Everything about this movie is from the mind o...,14 March 2013
3,ur23566468,tt0102813,5.0,Rover Dangerfield is loosely based on the late...,20 April 2020
4,ur4195782,tt0102813,3.0,I started out this movie with a positive attit...,8 August 2008
...,...,...,...,...,...
162072,ur1173088,tt0131704,4.0,The beginning of this movie is promising. It s...,29 June 2005
162073,ur2444068,tt0131704,5.0,Boris (Jason Alexander) and Natasha (Rene Russ...,20 January 2007
162074,ur0543054,tt0131704,5.0,"Somewhere in the heart of Frostbite Falls, our...",13 July 2000
162075,ur0631986,tt0131704,5.0,1st watched 3/10/2001 - (Dir-Des McAnuff) Humo...,10 March 2001
162076,ur0068788,tt0131704,10.0,I've been wanting to see this since I first he...,2 July 2001

In [10]:
print(len(ratings[ratings['rating'] == 1]))
print(len(ratings[ratings['rating'] == 2]))
print(len(ratings[ratings['rating'] == 3]))
print(len(ratings[ratings['rating'] == 4]))
print(len(ratings[ratings['rating'] == 5]))
print(len(ratings[ratings['rating'] == 6]))
print(len(ratings[ratings['rating'] == 7]))
print(len(ratings[ratings['rating'] == 8]))
print(len(ratings[ratings['rating'] == 9]))
print(len(ratings[ratings['rating'] == 10]))

7931
5726
7646
10285
15417
23021
28225
26774
16095
20957

In [11]:
import math
def normalizing_rating_score(score):
    return math.ceil(score / 2)

In [12]:
ratings['rating'] = ratings['rating'].apply(normalizing_rating_score)

In [13]:
print(len(ratings[ratings['rating'] == 1]))
print(len(ratings[ratings['rating'] == 2]))
print(len(ratings[ratings['rating'] == 3]))
print(len(ratings[ratings['rating'] == 4]))
print(len(ratings[ratings['rating'] == 5]))

13657
17931
38438
54999
37052

In [14]:
no_ratings_per_user = ratings.groupby('user id').count()['rating']

In [15]:
no_ratings_per_user

user id
ur0000011      1
ur0001220      2
ur0002746     10
ur0003136      5
ur0003696      6
              ..
ur99936512     1
ur99957464     1
ur99964320     2
ur99969779     1
ur99992944     1
Name: rating, Length: 22695, dtype: int64

In [16]:
user_ids = ratings.groupby('user id').count()['rating'].index.tolist()
user_ids = np.array(user_ids)

In [17]:
user_ids

array(['ur0000011', 'ur0001220', 'ur0002746', ..., 'ur99964320',
       'ur99969779', 'ur99992944'], dtype='<U11')

In [18]:
no_ratings_per_user = np.array(no_ratings_per_user)
user_id_idxes = np.argsort(no_ratings_per_user).tolist()

In [19]:
cnt = 0
for i in range(len(user_id_idxes[:1000])):
    idx = user_id_idxes[len(user_id_idxes) - i - 1]
    print(user_ids[idx], no_ratings_per_user[idx])

ur2898520 5163
ur4248714 3175
ur5876717 2996
ur0482513 2827
ur20552756 2622
ur2488512 2089
ur4888011 2025
ur1234929 1907
ur0453068 1901
ur77881167 1872
ur2467618 1687
ur2707735 1677
ur13977076 1621
ur22654354 1560
ur0945066 1547
ur4569900 1442
ur2483625 1311
ur0989035 1295
ur0449021 1269
ur3270789 1253
ur4445210 1138
ur0819382 1008
ur0278527 1001
ur3670492 990
ur7813355 970
ur16161013 929
ur2020269 901
ur5291991 820
ur60028700 817
ur2860723 803
ur3914439 795
ur2079400 794
ur69172350 790
ur0342623 784
ur33374263 782
ur76062573 776
ur2542703 722
ur107065132 711
ur0463200 696
ur1532177 688
ur28159509 678
ur58525162 663
ur11228318 626
ur22668817 615
ur23359813 594
ur18044142 571
ur0806494 566
ur1416505 561
ur0968789 560
ur22484170 551
ur15311310 541
ur29385135 530
ur2093818 528
ur15896852 527
ur8239592 517
ur2171244 511
ur0937743 498
ur9938570 494
ur3079504 489
ur104603847 487
ur3146136 486
ur1355507 481
ur0011762 480
ur4532636 477
ur15977902 424
ur1293485 403
ur1896124 393
ur12844960 393
ur71305899 364
ur34836174 351
ur50489624 347
ur1406078 345
ur1111192 325
ur23577930 325
ur44112735 322
ur26820801 317
ur0317399 315
ur25837689 307
ur3223254 303
ur4409266 301
ur100229298 299
ur23483288 297
ur8503729 293
ur79950921 293
ur1994077 292
ur57691865 289
ur0391152 277
ur9927546 276
ur0033913 275
ur2567136 274
ur5424352 274
ur17825945 273
ur36357573 270
ur64798417 267
ur22171966 262
ur23566468 256
ur25790270 244
ur49392790 234
ur64264987 232
ur23581966 232
ur0453228 230
ur1048771 225
ur5788055 222
ur1219578 221
ur43949288 221
ur1399158 219
ur1617546 215
ur11423174 213
ur2582239 211
ur79683341 206
ur3967726 205
ur14520497 204
ur39517558 204
ur64160263 200
ur2955724 198
ur49848930 198
ur25775215 194
ur54314810 194
ur33907744 189
ur1697212 189
ur79460801 189
ur34845698 181
ur2444068 178
ur4405474 177
ur13538926 176
ur0783721 175
ur56005872 173
ur15148330 173
ur11523087 170
ur0437174 170
ur8462477 170
ur6201371 170
ur1406466 164
ur17559480 164
ur71506838 163
ur1888886 162
ur20327151 160
ur1173088 158
ur6141756 156
ur0715971 155
ur31328960 154
ur0972645 154
ur40547513 152
ur2248099 152
ur2095936 152
ur32764997 151
ur68519886 150
ur66601046 150
ur3793011 148
ur4067661 147
ur12596887 146
ur1162550 144
ur94289145 144
ur34307814 143
ur23589178 143
ur34226907 143
ur0345596 140
ur23018536 139
ur0650255 139
ur27175177 138
ur71501643 137
ur78277499 136
ur131783850 136
ur15298231 135
ur82872124 135
ur55640799 134
ur2082018 134
ur2263198 132
ur68881398 130
ur4944007 129
ur17816293 129
ur19752191 128
ur58792324 127
ur19892892 126
ur6387867 125
ur34435688 124
ur18970655 123
ur0375636 123
ur48560127 122
ur17901972 120
ur0386241 119
ur0547823 119
ur59627333 118
ur125168510 118
ur48675674 118
ur1773414 117
ur23138767 117
ur57590728 117
ur25217752 117
ur4593705 116
ur3836774 116
ur130195767 114
ur34049683 113
ur1683855 111
ur79190944 110
ur91315068 109
ur24085266 108
ur98906416 108
ur84596117 108
ur27582881 106
ur3071695 106
ur12048299 106
ur24931284 106
ur69864183 103
ur0663392 101
ur2745984 100
ur23055365 99
ur78948186 99
ur69745746 98
ur73668075 97
ur50296294 96
ur20309759 96
ur28260582 96
ur1616919 96
ur71516783 95
ur6325108 94
ur0865972 94
ur49400835 93
ur119082541 92
ur117926588 92
ur22761455 92
ur85371862 92
ur0102816 92
ur26578226 90
ur0331289 90
ur6251613 89
ur0872211 88
ur4234119 88
ur29107311 87
ur6587670 86
ur52600820 85
ur84924605 84
ur12682317 83
ur35635716 82
ur34187486 81
ur2929860 81
ur2403537 81
ur0101706 81
ur0892646 80
ur104021780 80
ur13211310 80
ur113506463 80
ur22487163 80
ur12332223 80
ur78018459 79
ur6918917 79
ur8131454 78
ur105954145 78
ur68345682 77
ur15795433 77
ur17646017 76
ur0351766 74
ur1257208 73
ur30163554 73
ur44588015 73
ur34967775 72
ur111092901 72
ur112380085 71
ur4915915 70
ur3109237 69
ur1355003 69
ur67902729 69
ur66111139 69
ur71356826 69
ur2626332 69
ur4103165 68
ur1980092 68
ur7826013 68
ur116970440 67
ur2843647 67
ur30872044 66
ur30077883 65
ur4465293 65
ur25057297 65
ur118439842 65
ur45707659 65
ur74113527 65
ur7850750 64
ur29500838 64
ur25552762 63
ur89333699 63
ur49074014 62
ur23188638 62
ur23887409 62
ur55157303 61
ur75340345 61
ur7743887 61
ur142375144 61
ur126619686 61
ur113268676 61
ur14295241 60
ur51094543 60
ur18723110 59
ur35944897 59
ur60227834 59
ur87068272 57
ur6305926 57
ur1931604 56
ur53053227 56
ur60965299 55
ur48282208 55
ur85976313 55
ur78375856 55
ur8271923 54
ur94560739 54
ur49392222 54
ur83178856 54
ur20231624 54
ur47204983 53
ur4145136 52
ur23183310 52
ur50463365 52
ur30091810 52
ur91222832 51
ur88270629 51
ur134783880 51
ur3225430 51
ur87786768 51
ur0070535 50
ur2154134 50
ur51181843 50
ur44482045 50
ur5348015 50
ur27361979 50
ur0850869 50
ur13371508 49
ur121340923 49
ur103498042 48
ur24907049 48
ur46915265 48
ur53388186 48
ur125007632 48
ur3501803 47
ur82784830 47
ur57284019 47
ur41285353 47
ur32544613 47
ur23831210 47
ur82146887 46
ur81499083 46
ur13630333 46
ur31098854 46
ur1964495 46
ur68133936 46
ur68532916 46
ur24365278 46
ur25226117 46
ur71272418 46
ur8201706 46
ur86595662 46
ur66711472 46
ur70346195 46
ur70609419 45
ur17087537 45
ur26030604 45
ur18338773 45
ur17732486 45
ur9516916 44
ur55513445 44
ur90278387 44
ur1588706 43
ur0509769 43
ur8062935 43
ur23318905 43
ur0874373 43
ur27343685 43
ur112657298 43
ur61206453 43
ur61891359 42
ur32235533 42
ur26163020 42
ur43363139 42
ur57285538 42
ur52569309 42
ur22956348 41
ur46919419 41
ur24207434 41
ur0812029 41
ur40032021 41
ur25312605 41
ur3580907 41
ur44661012 41
ur20961309 40
ur24054983 40
ur14630819 40
ur35502638 40
ur102601261 40
ur2366174 40
ur35725947 40
ur3280905 39
ur81031037 39
ur1369762 39
ur3741220 39
ur1090944 39
ur2590596 39
ur37533654 39
ur17571044 39
ur10115739 39
ur101705202 39
ur45288585 39
ur111426842 39
ur58619720 39
ur34738421 39
ur1159678 39
ur17924275 39
ur29002389 38
ur12161715 38
ur28071275 38
ur79796304 38
ur118284470 38
ur26083589 38
ur23240045 38
ur4834714 37
ur58781741 37
ur91490177 37
ur2484839 37
ur109685083 37
ur74931296 37
ur53576145 37
ur93064197 37
ur98571307 37
ur1803589 36
ur125953851 36
ur10774147 36
ur91189245 36
ur20060108 36
ur126911477 36
ur94671559 36
ur23858655 36
ur14095545 36
ur5177700 36
ur1634796 36
ur8977071 36
ur51294955 36
ur11358734 35
ur41485753 35
ur118665987 35
ur1530907 35
ur85220553 35
ur0442119 35
ur2609601 35
ur98786654 35
ur87850731 35
ur0631986 35
ur4195782 35
ur22652704 34
ur12527639 34
ur77092838 34
ur54906652 34
ur13288300 34
ur65737204 34
ur10357384 34
ur26579233 34
ur83822756 34
ur69892343 34
ur1132073 34
ur69153149 34
ur0879559 33
ur111005416 33
ur62660431 33
ur22864666 33
ur67325954 33
ur10067675 32
ur29755759 32
ur113370202 32
ur107340115 32
ur38492175 32
ur87748969 32
ur120321993 32
ur0361658 32
ur58195064 32
ur55939461 32
ur126266447 31
ur2904081 31
ur106279729 31
ur15711750 31
ur53732923 31
ur48961864 31
ur16336334 31
ur85162534 31
ur12740916 31
ur20402944 31
ur27077890 31
ur117097528 31
ur0562732 30
ur45390749 30
ur83607055 30
ur73109146 30
ur23402006 30
ur102732419 30
ur22206328 30
ur15651776 30
ur79431623 30
ur47100167 30
ur0855231 30
ur42414764 29
ur61702090 29
ur84682955 29
ur133290271 29
ur102184407 29
ur69878054 29
ur104763420 29
ur26639083 29
ur65205095 29
ur0491610 29
ur5466406 29
ur34410526 29
ur1148847 29
ur19998007 29
ur30753782 29
ur107152571 29
ur18437585 29
ur113529171 29
ur0583640 29
ur6025018 28
ur44306450 28
ur49080270 28
ur45461313 28
ur22996114 28
ur61568240 28
ur24593235 28
ur13887584 28
ur39634854 28
ur110143882 28
ur85564866 28
ur19278556 28
ur3056473 28
ur22826047 27
ur69858713 27
ur31117020 27
ur15588823 27
ur40016938 27
ur57213624 27
ur86505257 27
ur74108860 27
ur87984636 27
ur90265605 27
ur102222939 27
ur13035875 27
ur28095258 27
ur80775867 27
ur104081577 27
ur20597848 27
ur85483078 27
ur46685920 27
ur112035303 26
ur47246436 26
ur20748638 26
ur4669024 26
ur78573336 26
ur18423640 26
ur130506467 26
ur16126010 26
ur1370070 26
ur2709206 26
ur105856169 26
ur103624323 26
ur2293681 26
ur139168789 26
ur74935180 26
ur20096899 26
ur67430579 26
ur25263169 26
ur67306446 26
ur106007927 26
ur54692175 26
ur79317583 26
ur52993466 26
ur1602433 25
ur0538858 25
ur87984559 25
ur15375264 25
ur5946448 25
ur0090767 25
ur62249628 25
ur6739749 25
ur98727037 25
ur1064827 25
ur125934623 25
ur27018907 25
ur59110401 25
ur24755804 25
ur98824201 25
ur22003481 25
ur0225436 25
ur62460576 25
ur103468007 25
ur0730388 25
ur47382469 25
ur0350076 25
ur22186567 25
ur53814270 25
ur87946145 24
ur26266323 24
ur59144688 24
ur55597043 24
ur11335477 24
ur67478381 24
ur48427941 24
ur63251546 24
ur4294858 24
ur126952560 24
ur96002443 24
ur77838279 24
ur81864032 24
ur60195330 24
ur61194652 24
ur41031967 24
ur119939766 24
ur18946496 24
ur2419668 24
ur32568896 24
ur61706810 24
ur1696608 24
ur0792758 24
ur4580541 24
ur67595110 24
ur127155319 24
ur16773950 24
ur115227177 23
ur5115203 23
ur75875398 23
ur97978800 23
ur0165374 23
ur44717123 23
ur122397455 23
ur80691527 23
ur19392148 23
ur5232724 23
ur5625948 23
ur131101255 23
ur6927864 23
ur47190847 23
ur5526520 23
ur104563194 23
ur99782462 23
ur64990197 23
ur38215575 23
ur0826090 23
ur91998110 23
ur17471213 23
ur2950235 23
ur87042890 23
ur82016772 23
ur75193729 23
ur11215533 23
ur124770392 23
ur40512810 23
ur2166662 23
ur121054481 23
ur108282385 23
ur55322044 23
ur52251585 23
ur40516374 23
ur22982565 23
ur42927804 23
ur0111731 23
ur58232116 23
ur20336887 22
ur60545327 22
ur1966301 22
ur23304576 22
ur3072427 22
ur18431344 22
ur27637510 22
ur5268350 22
ur64604296 22
ur86230128 22
ur88708820 22
ur54023586 22
ur2706684 22
ur60068164 22
ur54867897 22
ur54176053 22
ur17389661 22
ur3886859 22
ur23281514 22
ur72164454 22
ur3588397 22
ur46647047 22
ur9227049 22
ur1192722 22
ur69980801 22
ur67945761 22
ur38614372 22
ur89370109 21
ur2904674 21
ur6981752 21
ur59376203 21
ur9987799 21
ur16750431 21
ur88373850 21
ur4512019 21
ur5392144 21
ur3610419 21
ur1581184 21
ur3608743 21
ur68045216 21
ur23365095 21
ur0637715 21
ur60027662 21
ur21404273 21
ur19511193 21
ur0064493 21
ur20250079 21
ur8046532 21
ur57765841 21
ur31261952 21
ur0178741 21
ur88923138 21
ur135212298 21
ur55225553 21
ur3513409 21
ur28911673 21
ur2021461 21
ur86674245 21
ur48779501 21
ur106735135 21
ur70682706 20
ur99479682 20
ur46356078 20
ur114205379 20
ur82002563 20
ur17731534 20
ur94986533 20
ur67651029 20
ur57088858 20
ur56957037 20
ur99809306 20
ur19484559 20
ur0204528 20
ur85901673 20
ur68176810 20
ur18449099 20
ur101559732 20
ur1062771 20
ur56526203 20
ur1609501 20
ur12144093 20
ur6643268 20
ur29565770 20
ur2721657 20
ur16558990 20
ur25694706 20
ur47630115 20
ur20962118 20
ur32680209 20
ur57189960 19
ur67801172 19
ur65932704 19
ur57198382 19
ur41552750 19
ur32512011 19
ur66427619 19
ur98088930 19
ur43666830 19
ur0495697 19
ur5108679 19
ur117202813 19
ur13566917 19
ur48308797 19
ur127985847 19
ur66979966 19
ur105506099 19
ur94005246 19
ur39696525 19
ur52856345 19
ur32545718 19
ur111412436 19
ur0543054 19
ur1677427 19
ur20506225 19
ur82462880 19
ur2613818 19
ur77131575 19
ur15104159 19
ur109374849 19
ur1517556 19
ur73908325 19
ur118728304 19
ur1985363 19
ur19023771 19
ur0394025 19
ur7048882 19
ur11901761 18
ur105082429 18
ur57396250 18
ur1100711 18
ur58133193 18
ur66106173 18
ur28237482 18
ur57396192 18
ur24390444 18
ur1596808 18
ur65256868 18
ur91940320 18
ur26154754 18
ur0222418 18
ur100698011 18
ur3582979 18
ur10501479 18
ur110145410 18
ur0312444 18
ur3329978 18
ur55056252 18
ur16749093 18
ur4258330 18
ur15462771 18
ur19897085 18
ur42434289 18
ur23853676 18
ur53475492 18
ur35343017 18
ur48432998 18
ur69620564 18
ur6663090 18
ur14678985 18
ur3332368 18
ur68159882 18
ur71629917 18
ur19868562 18
ur69946382 18
ur80922659 18
ur51507991 18
ur29496881 18
ur67334856 18
ur19368298 18
ur15112828 17
ur0955440 17
ur77085352 17
ur122781086 17
ur10384462 17
ur1113856 17
ur43600791 17
ur5175792 17
ur26835138 17
ur4006751 17
ur1977084 17
ur27125033 17
ur0137908 17
ur89572875 17
ur3578650 17
ur8929656 17
ur99519886 17
ur14702719 17
ur102431840 17
ur50241333 17
ur69239269 17
ur36422659 17
ur115774856 17
ur111831007 17
ur15445210 17
ur6177494 17
ur46717069 17
ur36590018 17
ur47246324 17
ur75650931 17
ur3783846 17
ur50107221 17
ur62452126 17
ur0347711 17
ur78310344 17
ur58898824 17
ur54330302 17
ur8167945 17
ur54011929 17
ur90845220 17
ur3966946 17
ur61124370 17
ur89493617 17
ur21881328 17
ur64376466 17
ur24181359 17
ur1935875 17
ur16567048 16
ur66690288 16
ur79118814 16
ur92315547 16
ur80693802 16
ur1046557 16
ur59844801 16
ur74022315 16
ur41730297 16
ur69427158 16
ur9488819 16
ur78542739 16
ur89269798 16
ur107273206 16
ur109023433 16
ur69481828 16
ur7383416 16
ur6302267 16
ur67826053 16
ur92127176 16
ur43219975 16
ur21110209 16
ur5153691 16
ur58672953 16
ur91525484 16
ur71100372 16
ur12680645 16
ur82396246 16
ur3666644 16
ur1893630 16
ur116641944 16
ur85802235 16
ur68612934 16
ur2216443 16
ur1738956 16
ur124402254 16
ur25126113 16
ur34443949 16
ur0489763 16
ur60946497 16
ur15060576 16
ur108851030 16
ur89584137 16
ur63469855 16
ur129636274 16
ur9414155 16
ur2496397 16
ur108426522 16
ur24357805 15
ur1444027 15
ur34790048 15
ur11701403 15
ur79273104 15
ur0327799 15
ur14236266 15
ur8625456 15
ur47816750 15
ur95950840 15
ur1332263 15
ur28643054 15
ur109188739 15
ur4101690 15
ur109505309 15
ur2306546 15
ur24171148 15
ur2862544 15
ur53582442 15
ur118562022 15
ur50306943 15
ur37568851 15
ur104062880 15
ur81872808 15
ur116666293 15
ur133004424 15
ur58341098 15
ur0097585 15
ur13863190 15
ur80388571 15
ur65673698 15
ur90750895 15
ur49417836 15
ur37365377 15
ur3530868 15
ur8766134 15
ur4555280 15
ur21618942 15
ur114026501 15
ur13269908 15
ur4980432 15
ur65491461 15
ur0689691 15
ur37569728 15
ur2722583 15
ur29589601 15
ur82980682 15
ur24673102 15
ur14477953 15
ur102935740 15
ur70587126 15
ur37647343 15
ur1004378 15
ur125176958 15
ur110936802 15
ur119716047 15
ur65374826 15
ur35669238 15
ur22008076 14
ur53096283 14
ur23129480 14
ur103297681 14
ur13401764 14
ur62933173 14
ur5755522 14
ur23501644 14
ur3619160 14
ur112666300 14
ur18913786 14
ur14080241 14
ur67641546 14
ur19048737 14
ur24230755 14
ur3443744 14
ur92678607 14
ur2747461 14
ur15140057 14
ur26149494 14

In [20]:
eliminated_user_ids = user_ids[user_id_idxes[:-1000]].tolist() + user_ids[user_id_idxes[-10:]].tolist()

In [21]:
eliminated_user_ids

['ur0000011',
 'ur3958569',
 'ur39586391',
 'ur3958905',
 'ur39593965',
 'ur39613089',
 'ur3961523',
 'ur39617778',
 'ur3962446',
 'ur39625042',
 'ur39627788',
 'ur39629985',
 'ur39651438',
 'ur39666446',
 'ur3967706',
 'ur39700283',
 'ur39701710',
 'ur39742510',
 'ur39942159',
 'ur39941527',
 'ur39916668',
 'ur3991196',
 'ur39897231',
 'ur39881777',
 'ur39578666',
 'ur39866742',
 'ur39814016',
 'ur39784951',
 'ur39782431',
 'ur39755660',
 'ur3975379',
 'ur3974800',
 'ur39826292',
 'ur39575215',
 'ur3957278',
 'ur3956608',
 'ur39386116',
 'ur39373542',
 'ur39372658',
 'ur39372103',
 'ur39371100',
 'ur39363303',
 'ur39404893',
 'ur3934542',
 'ur39294476',
 'ur39277869',
 'ur3925940',
 'ur3924830',
 'ur3924378',
 'ur39220576',
 'ur39316610',
 'ur3995134',
 'ur39404946',
 'ur3942259',
 'ur39547256',
 'ur39546659',
 'ur39512004',
 'ur39509208',
 'ur39502622',
 'ur39498854',
 'ur39420312',
 'ur39476006',
 'ur3946292',
 'ur39456477',
 'ur39450712',
 'ur39447539',
 'ur39440084',
 'ur39431434',
 'ur39474700',
 'ur3995436',
 'ur39963847',
 'ur39964759',
 'ur4052658',
 'ur40515784',
 'ur4050371',
 'ur40496390',
 'ur40491494',
 'ur40489831',
 'ur40535840',
 'ur4048725',
 'ur40486253',
 'ur40485603',
 'ur40484199',
 'ur40457110',
 'ur4045001',
 'ur40448824',
 'ur40486654',
 'ur4044518',
 'ur4056498',
 'ur4057131',
 'ur40851900',
 'ur40842132',
 'ur4079580',
 'ur40760897',
 'ur40705076',
 'ur4069536',
 'ur40569876',
 'ur40675997',
 'ur4066644',
 'ur4065532',
 'ur4063030',
 'ur40618083',
 'ur40597143',
 'ur40580380',
 'ur40674212',
 'ur3921986',
 'ur4044135',
 'ur4042763',
 'ur40164759',
 'ur40157156',
 'ur40156720',
 'ur40152404',
 'ur40127150',
 'ur40122852',
 'ur40180934',
 'ur40118734',
 'ur40087125',
 'ur40064121',
 'ur40062084',
 'ur4005001',
 'ur40048969',
 'ur39994743',
 'ur40095620',
 'ur40432069',
 'ur4018185',
 'ur40193443',
 'ur4041647',
 'ur40401507',
 'ur40394977',
 'ur4039062',
 'ur4038386',
 'ur40350441',
 'ur40187529',
 'ur40350058',
 'ur40334566',
 'ur4032941',
 'ur4032014',
 'ur40273351',
 'ur40245857',
 'ur40236281',
 'ur40335639',
 'ur40855361',
 'ur39202833',
 'ur39184519',
 'ur38089771',
 'ur38097604',
 'ur38105069',
 'ur38105646',
 'ur38109226',
 'ur38139314',
 'ur3815068',
 'ur38164356',
 'ur38164521',
 'ur38200008',
 'ur38201586',
 'ur38209383',
 'ur38210190',
 'ur38211214',
 'ur38233565',
 'ur38238509',
 'ur38240527',
 'ur38371624',
 'ur38370237',
 'ur38365655',
 'ur38350789',
 'ur3831140',
 'ur38303615',
 'ur38087347',
 'ur38302862',
 'ur38294684',
 'ur38291721',
 'ur38288107',
 'ur38287285',
 'ur38272621',
 'ur38265915',
 'ur38297618',
 'ur38077550',
 'ur38076405',
 'ur38073921',
 'ur37897144',
 'ur37894823',
 'ur37864167',
 'ur37863187',
 'ur37845956',
 'ur37836657',
 'ur37926538',
 'ur37834951',
 'ur3782792',
 'ur37821170',
 'ur37820640',
 'ur37815634',
 'ur3780232',
 'ur37793921',
 'ur37829529',
 'ur38372033',
 'ur37927079',
 'ur37948302',
 'ur38066410',
 'ur38062222',
 'ur38038061',
 'ur3802362',
 'ur38021829',
 'ur38013435',
 'ur37932690',
 'ur38009993',
 'ur38001735',
 'ur3798706',
 'ur37984238',
 'ur37964935',
 'ur37957812',
 'ur37948701',
 'ur38003485',
 'ur38382579',
 'ur3838697',
 'ur38387953',
 'ur38944365',
 'ur38902676',
 'ur38887167',
 'ur38885237',
 'ur38881554',
 'ur3883151',
 'ur38956309',
 'ur38829860',
 'ur38809485',
 'ur38782596',
 'ur38771935',
 'ur38745400',
 'ur3873901',
 'ur38734646',
 'ur38814587',
 'ur38732856',
 'ur3900151',
 'ur39034888',
 'ur39174997',
 'ur3916175',
 'ur39154966',
 'ur39135335',
 'ur3911979',
 'ur39118228',
 'ur39006983',
 'ur39105025',
 'ur3909898',
 'ur39096432',
 'ur39070702',
 'ur39069560',
 'ur39055335',
 'ur39043979',
 'ur39099626',
 'ur3919673',
 'ur38715325',
 'ur3869264',
 'ur38505246',
 'ur38495249',
 'ur3848536',
 'ur38483821',
 'ur3847853',
 'ur3847551',
 'ur38511506',
 'ur38474774',
 'ur38468801',
 'ur38462067',
 'ur38452894',
 'ur38452821',
 'ur38404111',
 'ur38393877',
 'ur3847007',
 'ur38700285',
 'ur38519767',
 'ur3853258',
 'ur38668909',
 'ur38638081',
 'ur38633350',
 'ur38626450',
 'ur38619050',
 'ur3861837',
 'ur38521423',
 'ur3861229',
 'ur38598028',
 'ur38594429',
 'ur38578230',
 'ur3856716',
 'ur3856112',
 'ur38554699',
 'ur3860784',
 'ur40870871',
 'ur40875206',
 'ur40875238',
 'ur42674528',
 'ur42699890',
 'ur42736840',
 'ur42741462',
 'ur4275756',
 'ur4277036',
 'ur42780379',
 'ur42792864',
 'ur42805200',
 'ur42805967',
 'ur42821340',
 'ur4282743',
 'ur42827612',
 'ur42852405',
 'ur42857481',
 'ur42865403',
 'ur42874483',
 'ur42981607',
 'ur4298109',
 'ur42963874',
 'ur42959245',
 'ur42936359',
 'ur42930673',
 'ur42648577',
 'ur42927047',
 'ur4292332',
 'ur4291930',
 'ur4291019',
 'ur42905930',
 'ur42900667',
 'ur42891820',
 'ur42923646',
 'ur42644438',
 'ur42643642',
 'ur42634488',
 'ur42454330',
 'ur4244074',
 'ur42418897',
 'ur42418703',
 'ur42418381',
 'ur42406644',
 'ur4245956',
 'ur42405604',
 'ur42400144',
 'ur42397709',
 'ur42391823',
 'ur4239129',
 'ur4237656',
 'ur4237030',
 'ur42400929',
 'ur4299476',
 'ur42466355',
 'ur4249100',
 'ur4263310',
 'ur42618435',
 'ur42610474',
 'ur4261025',
 'ur42595310',
 'ur42591868',
 'ur4247440',
 'ur4259037',
 'ur42544132',
 'ur4254392',
 'ur42533229',
 'ur42531079',
 'ur42512993',
 'ur42504800',
 'ur4258793',
 'ur43025767',
 'ur4302606',
 'ur43028478',
 'ur43362027',
 'ur43353056',
 'ur43350397',
 'ur43350260',
 'ur43339086',
 'ur4333384',
 'ur43365781',
 'ur43333638',
 'ur43307557',
 'ur43298950',
 'ur4329394',
 'ur4329092',
 'ur43287001',
 'ur43284905',
 'ur43321502',
 'ur43275969',
 'ur4337792',
 'ur43397136',
 'ur43509066',
 'ur43484751',
 'ur4348330',
 'ur43482625',
 'ur43478906',
 'ur43468712',
 'ur43379499',
 'ur4346182',
 'ur4343882',
 'ur43437925',
 'ur43430812',
 'ur4342893',
 'ur43427047',
 'ur43401645',
 'ur43439785',
 'ur42359906',
 'ur43252987',
 'ur43247504',
 'ur43095084',
 'ur43091064',
 'ur43082120',
 'ur4307994',
 'ur43078905',
 'ur4307228',
 'ur43101015',
 'ur43066936',
 'ur4305679',
 'ur4305508',
 'ur43047838',
 'ur4304579',
 'ur43039441',
 'ur4303406',
 'ur43062079',
 'ur43252804',
 'ur43102122',
 'ur43130795',
 'ur43225569',
 'ur43219766',
 'ur43193586',
 'ur43174402',
 'ur4316459',
 'ur4316349',
 'ur4310851',
 'ur43155884',
 'ur43139960',
 'ur4313761',
 'ur43136984',
 'ur4313626',
 'ur43136118',
 'ur4313189',
 'ur43151561',
 'ur42358614',
 'ur42353295',
 'ur42337316',
 'ur41396631',
 'ur41390506',
 'ur41370957',
 'ur41366085',
 'ur41353868',
 'ur41350501',
 'ur41396688',
 'ur4134897',
 'ur41344191',
 'ur41335501',
 'ur41333282',
 'ur4133148',
 'ur4131759',
 'ur41307109',
 'ur41347824',
 'ur41297423',
 'ur41403972',
 'ur4142349',
 'ur41597765',
 'ur41593690',
 'ur41585330',
 'ur4155432',
 'ur4155019',
 'ur41531396',
 'ur41416455',
 'ur4150925',
 'ur41480153',
 'ur41456335',
 'ur41454311',
 'ur41450348',
 'ur4143098',
 'ur41425721',
 'ur41502012',
 'ur41598163',
 'ur4128586',
 'ur41253443',
 'ur41005661',
 'ur41002500',
 'ur40993827',
 'ur40979376',
 'ur40966408',
 'ur40958773',
 'ur41006061',
 'ur40935972',
 'ur40909081',
 'ur40908524',
 'ur40907898',
 'ur4090760',
 'ur4089410',
 'ur40893447',
 'ur40925831',
 'ur41261178',
 'ur41043978',
 'ur41065012',
 'ur41243073',
 'ur41230166',
 'ur4122152',
 'ur41211554',
 'ur4119395',
 'ur41188502',
 'ur41045995',
 'ur41129353',
 'ur4110821',
 'ur41095470',
 'ur41091412',
 'ur41080852',
 'ur41072641',
 'ur41070531',
 'ur41117293',
 'ur37790147',
 'ur41607422',
 'ur4162450',
 'ur4210720',
 'ur4209792',
 'ur42094438',
 'ur42064593',
 'ur4205035',
 'ur4203252',
 'ur42112015',
 'ur42025123',
 'ur42023342',
 'ur42017980',
 'ur4201650',
 'ur42015717',
 'ur42014809',
 'ur42008254',
 'ur42024805',
 'ur4198083',
 'ur42121138',
 'ur42127167',
 'ur42331917',
 'ur42326686',
 'ur42325674',
 'ur4232115',
 'ur4228845',
 'ur42275343',
 'ur4212679',
 'ur42259189',
 'ur42229856',
 'ur4222122',
 'ur42218499',
 'ur42210560',
 'ur42203875',
 'ur42137495',
 'ur42232757',
 'ur41608946',
 'ur41958000',
 'ur41905965',
 'ur4171304',
 'ur41704851',
 'ur41677471',
 'ur4167371',
 'ur41670709',
 'ur41670195',
 'ur4171750',
 'ur41665185',
 'ur41650708',
 'ur41647858',
 'ur41647568',
 'ur4163028',
 'ur41626254',
 'ur41625676',
 'ur41659222',
 'ur4195761',
 'ur41751279',
 'ur41766416',
 'ur41904755',
 'ur4190035',
 'ur4189378',
 'ur41887526',
 'ur41880988',
 'ur41874650',
 'ur41760481',
 'ur4184582',
 'ur41822616',
 'ur41813384',
 'ur4181021',
 'ur41809562',
 'ur41807933',
 'ur41782044',
 'ur4184177',
 'ur43510416',
 'ur37773889',
 'ur37766394',
 'ur34740948',
 'ur3474218',
 'ur34753948',
 'ur34757370',
 'ur34760451',
 'ur3476362',
 'ur34763688',
 'ur3476529',
 'ur3477123',
 'ur34772665',
 'ur34772966',
 'ur3477630',
 'ur34781481',
 'ur34781913',
 'ur3478531',
 'ur34787860',
 'ur34788928',
 'ur3496214',
 'ur3495096',
 'ur3494987',
 'ur3494875',
 'ur3494481',
 'ur34934866',
 'ur3473506',
 'ur34926187',
 'ur34916740',
 'ur3487947',
 'ur3487897',
 'ur34852431',
 'ur34829214',
 'ur3479720',
 'ur34918978',
 'ur34728869',
 'ur34714931',
 'ur34709744',
 'ur34627686',
 'ur34583623',
 'ur3454783',
 'ur34538167',
 'ur34533969',
 'ur34529716',
 'ur3463277',
 'ur34526546',
 'ur3449166',
 'ur34484559',
 'ur34479440',
 'ur34478194',
 'ur34472201',
 'ur3447130',
 'ur34522146',
 'ur34971261',
 'ur34633235',
 'ur34640984',
 'ur34708904',
 'ur34708045',
 'ur34707127',
 'ur34700641',
 'ur34699238',
 'ur34690236',
 'ur34640565',
 'ur34677199',
 'ur34664440',
 'ur34659610',
 'ur3465461',
 'ur3465286',
 'ur34645153',
 'ur34643786',
 'ur34670923',
 'ur34990042',
 'ur34994233',
 'ur34997457',
 'ur3533619',
 'ur35332683',
 'ur3532744',
 'ur35321305',
 'ur35319297',
 'ur35303495',
 'ur3533665',
 'ur35293676',
 'ur35290098',
 'ur3528918',
 'ur35282109',
 'ur35278180',
 'ur35275541',
 'ur35259888',
 'ur35290402',
 'ur35230749',
 'ur35337575',
 'ur35338627',
 'ur35390984',
 'ur35389042',
 'ur3538081',
 'ur35374643',
 'ur3537214',
 'ur35364895',
 'ur35338085',
 'ur35364245',
 'ur35360817',
 'ur35356355',
 'ur35353732',
 'ur35353030',
 'ur3535282',
 'ur35344987',
 'ur35362031',
 'ur34469922',
 'ur35230659',
 'ur35221390',
 'ur3510488',
 'ur35100388',
 'ur35082332',
 'ur35078517',
 'ur35071580',
 'ur35067890',
 'ur35113939',
 'ur35048853',
 'ur35040447',
 'ur35037678',
 'ur35023824',
 'ur35013590',
 'ur35009569',
 'ur34998489',
 'ur35046219',
 'ur35221967',
 'ur3511557',
 'ur35129512',
 'ur35219528',
 'ur35216414',
 'ur35214878',
 'ur35211725',
 'ur3520855',
 'ur3519967',
 'ur35118533',
 'ur35177660',
 'ur35160125',
 'ur35151746',
 'ur35147784',
 'ur3514009',
 'ur35138110',
 'ur35135094',
 'ur3516749',
 'ur35394408',
 'ur3446880',
 'ur3446015',
 'ur33727686',
 'ur33745898',
 'ur33747978',
 'ur33749929',
 'ur3375665',
 'ur33763615',
 'ur33767024',
 'ur3379318',
 'ur33796273',
 'ur33796675',
 'ur33806943',
 'ur33815826',
 'ur33816424',
 'ur33824650',
 'ur33841674',
 'ur3384697',
 'ur33849017',
 'ur33937288',
 'ur33933447',
 'ur3392420',
 'ur33922346',
 'ur33921533',
 'ur33921339',
 'ur33704671',
 'ur33918074',
 'ur33906383',
 'ur3388868',
 'ur3387906',
 'ur33875393',
 'ur3385396',
 'ur33852262',
 'ur33912713',
 'ur33686744',
 'ur33669547',
 'ur33664558',
 'ur33549740',
 'ur33533012',
 'ur33528537',
 'ur33524359',
 'ur33495635',
 'ur33490508',
 'ur33553709',
 'ur33487742',
 'ur3348423',
 'ur33479845',
 'ur33479030',
 'ur33469956',
 'ur33450054',
 'ur33446785',
 'ur33487739',
 'ur33939715',
 'ur33573288',
 'ur33588275',
 'ur33655060',
 'ur33654957',
 'ur3365452',
 'ur3365359',
 'ur33646645',
 'ur3364165',
 'ur33583038',
 'ur33631906',
 'ur3362906',
 'ur33628252',
 'ur33612602',
 'ur3359262',
 'ur33590941',
 'ur3358963',
 'ur33629204',
 'ur3394600',
 'ur33946433',
 'ur3394782',
 'ur34299527',
 'ur34297246',
 'ur3429682',
 'ur3429462',
 'ur34287413',
 'ur3427339',
 'ur3431829',
 'ur34270927',
 'ur34252624',
 'ur34248745',
 'ur34245901',
 'ur34242037',
 'ur34233142',
 'ur34230845',
 'ur34268976',
 'ur34230668',
 'ur34320676',
 'ur34344275',
 'ur34458574',
 'ur34437502',
 'ur34413319',
 'ur34405230',
 'ur3439700',
 'ur34396905',
 'ur34321835',
 'ur34393686',
 'ur34387313',
 'ur34356019',
 'ur3435595',
 'ur34355866',
 'ur3435578',
 'ur3435249',
 'ur34389953',
 'ur3446219',
 'ur34226510',
 'ur34185309',
 'ur34071800',
 'ur34048690',
 'ur34031838',
 'ur34024454',
 'ur34020277',
 'ur34011150',
 'ur34079915',
 'ur3400939',
 'ur34007948',
 'ur33979288',
 'ur33977568',
 'ur3397538',
 'ur3396918',
 'ur33962720',
 'ur34008987',
 'ur34206383',
 'ur34080302',
 'ur34095058',
 'ur34185292',
 'ur3418446',
 'ur34176589',
 'ur3416554',
 'ur34163921',
 'ur34158321',
 'ur34088645',
 'ur34153764',
 'ur34140122',
 'ur34139934',
 'ur3412905',
 'ur34122475',
 'ur34117290',
 'ur34101427',
 'ur34144457',
 'ur35412772',
 'ur35417169',
 'ur3542567',
 'ur36924932',
 'ur3692943',
 'ur36932906',
 'ur36933524',
 'ur36936371',
 'ur36946380',
 'ur36965270',
 'ur3697259',
 'ur36972811',
 'ur3697417',
 'ur36982467',
 'ur36992156',
 'ur36997112',
 'ur3700493',
 'ur37007201',
 'ur37007480',
 'ur37023081',
 'ur37143810',
 'ur37133414',
 'ur37126650',
 'ur37111472',
 'ur37106694',
 'ur37089839',
 'ur36922988',
 'ur37085494',
 'ur37064232',
 'ur37059740',
 'ur37051495',
 'ur37037162',
 'ur37035000',
 'ur3703068',
 'ur37068902',
 'ur3692279',
 'ur36910665',
 'ur36908998',
 'ur36694829',
 'ur3668951',
 'ur36673610',
 'ur36671058',
 'ur3666966',
 'ur36669226',
 'ur36696791',
 'ur36635916',
 'ur36617519',
 'ur36610443',
 'ur36607678',
 'ur36593210',
 'ur36593051',
 'ur36578783',
 'ur36620149',
 'ur37148578',
 'ur36699873',
 'ur36718932',
 'ur36886383',
 'ur36865478',
 'ur36849886',
 'ur36848347',
 'ur36824259',
 'ur36823164',
 'ur36702198',
 'ur36814009',
 'ur36802151',
 'ur36784529',
 'ur3676745',
 'ur36746936',
 'ur36745914',
 'ur36745082',
 'ur3681150',
 'ur37149769',
 'ur37152286',
 'ur3716009',
 'ur37560151',
 'ur37540948',
 'ur37531636',
 'ur37510995',
 'ur3750956',
 'ur3750839',
 'ur37564876',
 'ur3750285',
 'ur37493212',
 'ur37484002',
 'ur37469509',
 'ur37463788',
 'ur37451936',
 'ur37445176',
 'ur37495304',
 'ur37443617',
 'ur37575825',
 'ur3760162',
 'ur37745094',
 'ur37741378',
 'ur37730013',
 'ur37722557',
 'ur37713470',
 'ur37688824',
 'ur37588642',
 'ur37679656',
 'ur3766841',
 'ur37665181',
 'ur3765956',
 'ur37659127',
 'ur37646496',
 'ur37613412',
 'ur37676396',
 'ur36575767',
 'ur3744316',
 'ur37420309',
 'ur37233250',
 'ur37219855',
 'ur37216683',
 'ur37215902',
 'ur37215706',
 'ur3721305',
 'ur37247187',
 'ur37212899',
 'ur37191963',
 'ur3718062',
 'ur37178773',
 'ur37173139',
 'ur37165226',
 'ur3716389',
 'ur3720718',
 'ur37426775',
 'ur37249022',
 'ur37254808',
 'ur37417060',
 'ur3740966',
 'ur37405910',
 'ur37399015',
 'ur37391798',
 'ur37383133',
 'ur37251647',
 'ur3736826',
 'ur37358841',
 'ur37326559',
 'ur37323997',
 'ur37322650',
 'ur3729962',
 'ur37294062',
 'ur37359826',
 ...]

In [22]:
eliminated_user_ids_df = pd.DataFrame(columns=['user id'])
eliminated_user_ids_df['user id'] = eliminated_user_ids

In [23]:
eliminated_user_ids_df.head()

      user id
0   ur0000011
1   ur3958569
2  ur39586391
3   ur3958905
4  ur39593965

In [24]:
eliminated_ratings_df = pd.merge(ratings, eliminated_user_ids_df, how='inner', left_on='user id', right_on='user id')
eliminated_ratings_df

,user id,movie id,rating,content,date
0,ur20552756,tt0102813,3,I am a big fan of animated movies and of anima...,22 June 2011
1,ur20552756,tt0075686,5,"Not everybody will love Woody Allen's humour, ...",9 February 2014
2,ur20552756,tt0207120,2,"I like Spider-Man a great deal, I do like the ...",23 September 2012
3,ur20552756,tt1402488,2,I want to start off saying that I liked the fi...,10 March 2012
4,ur20552756,tt0857277,4,"Just last night, I was replying to a thread on...",8 August 2010
...,...,...,...,...,...
65478,ur86632441,tt10642154,5,I loved it! I've watched it alot! Love Melissa...,19 November 2020
65479,ur33402437,tt10642154,4,If you watch a Lifetime or Hallmark Christmas ...,10 November 2019
65480,ur73282794,tt10642154,4,"While not an award winner, this was pretty enj...",10 November 2019
65481,ur124415538,tt10642154,5,I enjoyed the movie due to the wonderful stars...,19 September 2020
65482,ur8379971,tt10642154,1,"Oversentimental, maudlin, cloying, sickly, sac...",22 November 2019

In [25]:
eliminated_ratings_df.to_csv('../data/datasets/rating/dropped_detail.csv', sep=',', encoding='latin-1', index=False)

In [26]:
remaining_user_ids = user_ids[user_id_idxes[-1400:-10]]
print(len(remaining_user_ids))
remaining_user_ids

1390

array(['ur7868777', 'ur117501204', 'ur3260904', ..., 'ur13977076',
       'ur2707735', 'ur2467618'], dtype='<U11')

In [27]:
remaining_user_ids_df = pd.DataFrame(columns=['user id'])
remaining_user_ids_df['user id'] = remaining_user_ids

In [28]:
remaining_user_ids_df.head()

       user id
0    ur7868777
1  ur117501204
2    ur3260904
3   ur18271419
4   ur53568182

In [29]:
remaining_ratings_df = pd.merge(ratings, remaining_user_ids_df, how='inner', left_on='user id', right_on='user id')
remaining_ratings_df

,user id,movie id,rating,content,date
0,ur0391152,tt0102813,2,I've always had kind of a perverse curiosity a...,22 August 2010
1,ur0391152,tt0387808,5,20th Century Fox was moronic not to release th...,6 November 2006
2,ur0391152,tt0845046,5,It's the kind of movie that reminds me that th...,28 September 2008
3,ur0391152,tt0113824,5,"A very moving animÃƒÂ© film from Studio Ghibli, ...",29 September 2003
4,ur0391152,tt0455538,2,Based on the autobiographical tale of writer T...,6 October 2008
...,...,...,...,...,...
101216,ur23466126,tt3596174,1,I happened to watch a few episodes a couple of...,20 October 2021
101217,ur23466126,tt6807662,3,Um ... I have to admit it's interesting. The s...,11 November 2020
101218,ur23466126,tt4145054,2,"So the first scenes are full of popped lips, p...",11 December 2020
101219,ur23466126,tt8103070,2,When I watch this series I have the feeling th...,5 August 2020
101220,ur23466126,tt1429449,2,I don't know if I would categorize this as a t...,31 August 2020

In [30]:
remaining_ratings_df['movie id'].unique()

array(['tt0102813', 'tt0387808', 'tt0845046', ..., 'tt9721776',
       'tt4648640', 'tt8045690'], dtype=object)

In [31]:
len(remaining_ratings_df['movie id'].unique())

9370

In [32]:
movie_ids = remaining_ratings_df['movie id'].value_counts().index.tolist()

In [33]:
movie_ids

['tt1837492',
 'tt12361178',
 'tt10752004',
 'tt1190634',
 'tt9544034',
 'tt11260832',
 'tt6473300',
 'tt1043813',
 'tt6156584',
 'tt7875794',
 'tt8425404',
 'tt10986410',
 'tt11651796',
 'tt8760932',
 'tt11027830',
 'tt5540054',
 'tt7212754',
 'tt9698480',
 'tt3921180',
 'tt5348176',
 'tt10888594',
 'tt10168312',
 'tt9359220',
 'tt7472896',
 'tt10207090',
 'tt8332438',
 'tt1733785',
 'tt8416494',
 'tt2303687',
 'tt11846996',
 'tt8923854',
 'tt8201186',
 'tt8772296',
 'tt5574490',
 'tt7902072',
 'tt2177461',
 'tt7908628',
 'tt0062883',
 'tt6857376',
 'tt10062292',
 'tt7658402',
 'tt7424200',
 'tt10350922',
 'tt8064302',
 'tt8697870',
 'tt11083696',
 'tt5363918',
 'tt2250192',
 'tt10228230',
 'tt2861424',
 'tt4998350',
 'tt7134908',
 'tt4276618',
 'tt3032476',
 'tt2403776',
 'tt10293938',
 'tt8110330',
 'tt4465572',
 'tt9860728',
 'tt5580146',
 'tt10096842',
 'tt9059350',
 'tt5562070',
 'tt6741278',
 'tt11750282',
 'tt7488208',
 'tt11794642',
 'tt10009170',
 'tt7569576',
 'tt7740510',
 'tt5774002',
 'tt9052870',
 'tt7335184',
 'tt7298596',
 'tt9179552',
 'tt9446688',
 'tt11815682',
 'tt11686490',
 'tt3281796',
 'tt9054904',
 'tt2937366',
 'tt2177268',
 'tt9182964',
 'tt10515988',
 'tt5748448',
 'tt11126994',
 'tt7660850',
 'tt10295212',
 'tt1869454',
 'tt3230854',
 'tt9140554',
 'tt11199410',
 'tt10696784',
 'tt12392504',
 'tt11284280',
 'tt6517102',
 'tt1104835',
 'tt5618256',
 'tt4508902',
 'tt4058836',
 'tt11946300',
 'tt2452242',
 'tt2707408',
 'tt4236770',
 'tt10834220',
 'tt4474344',
 'tt0060708',
 'tt8089592',
 'tt5114356',
 'tt4733624',
 'tt8295472',
 'tt13372794',
 'tt3007572',
 'tt6468322',
 'tt7985576',
 'tt8210856',
 'tt10793644',
 'tt0101757',
 'tt9251798',
 'tt3358020',
 'tt11307814',
 'tt9642938',
 'tt9055008',
 'tt9100822',
 'tt0489974',
 'tt8954732',
 'tt5071412',
 'tt7949218',
 'tt6394324',
 'tt7671598',
 'tt1526318',
 'tt7493974',
 'tt10795658',
 'tt6048596',
 'tt4976512',
 'tt8421350',
 'tt2531336',
 'tt9151230',
 'tt6616260',
 'tt5171438',
 'tt10234362',
 'tt2304589',
 'tt2049116',
 'tt5687612',
 'tt11656892',
 'tt4396630',
 'tt5011816',
 'tt8690918',
 'tt5555260',
 'tt1817771',
 'tt5626028',
 'tt8299768',
 'tt10220588',
 'tt2149175',
 'tt6794990',
 'tt7016936',
 'tt8962124',
 'tt5269594',
 'tt2386237',
 'tt9831136',
 'tt0475784',
 'tt8259142',
 'tt7949204',
 'tt1772250',
 'tt3626476',
 'tt11881160',
 'tt0110366',
 'tt0058743',
 'tt6508228',
 'tt2077823',
 'tt3498622',
 'tt12708542',
 'tt8119752',
 'tt9612516',
 'tt14867006',
 'tt12877640',
 'tt3118452',
 'tt6548228',
 'tt0460627',
 'tt5116302',
 'tt7616798',
 'tt13341414',
 'tt7440726',
 'tt0056059',
 'tt0393685',
 'tt10530176',
 'tt1740299',
 'tt10970552',
 'tt1104836',
 'tt1010271',
 'tt7569592',
 'tt5905354',
 'tt6866266',
 'tt0348333',
 'tt1839578',
 'tt4103724',
 'tt4682804',
 'tt5743796',
 'tt11214590',
 'tt9419056',
 'tt2838678',
 'tt4181172',
 'tt0051516',
 'tt10183816',
 'tt0039502',
 'tt4513678',
 'tt2661044',
 'tt11043632',
 'tt0386676',
 'tt7026488',
 'tt2675914',
 'tt2712740',
 'tt11394332',
 'tt1236246',
 'tt7073710',
 'tt0339840',
 'tt2261227',
 'tt8714904',
 'tt7120662',
 'tt1826940',
 'tt1196141',
 'tt8398600',
 'tt1312171',
 'tt9173154',
 'tt5180504',
 'tt9184986',
 'tt6474378',
 'tt1773185',
 'tt9794630',
 'tt8001106',
 'tt9683478',
 'tt8550800',
 'tt1034385',
 'tt7661390',
 'tt0877057',
 'tt0285728',
 'tt6571548',
 'tt9398640',
 'tt5149528',
 'tt3139086',
 'tt7177890',
 'tt6560164',
 'tt8385474',
 'tt6656238',
 'tt6556890',
 'tt10850932',
 'tt8721424',
 'tt9686194',
 'tt9426210',
 'tt1831804',
 'tt8103070',
 'tt12851524',
 'tt3749900',
 'tt6428676',
 'tt0080377',
 'tt9814116',
 'tt1094229',
 'tt13344860',
 'tt11100856',
 'tt8085790',
 'tt1494772',
 'tt8303474',
 'tt11079148',
 'tt11041132',
 'tt7203552',
 'tt6338498',
 'tt3398228',
 'tt7721800',
 'tt7909970',
 'tt0059557',
 'tt0094612',
 'tt4430212',
 'tt6378710',
 'tt7942796',
 'tt6510950',
 'tt11777040',
 'tt1267295',
 'tt9170108',
 'tt4334266',
 'tt7456722',
 'tt2820466',
 'tt8880894',
 'tt7058080',
 'tt2828996',
 'tt10327354',
 'tt4179452',
 'tt11390036',
 'tt6487482',
 'tt11778118',
 'tt11337862',
 'tt8510350',
 'tt4258440',
 'tt0385700',
 'tt5290382',
 'tt0096945',
 'tt2486678',
 'tt7217374',
 'tt5580540',
 'tt8594324',
 'tt10620868',
 'tt9772374',
 'tt11343600',
 'tt11242218',
 'tt8178650',
 'tt6611916',
 'tt5973626',
 'tt1595859',
 'tt11252440',
 'tt2788432',
 'tt15097216',
 'tt2741602',
 'tt1474684',
 'tt7060344',
 'tt5788792',
 'tt0067333',
 'tt6729080',
 'tt4326894',
 'tt3502248',
 'tt2193021',
 'tt6456326',
 'tt5420376',
 'tt0057007',
 'tt2249007',
 'tt5853176',
 'tt1648179',
 'tt9731534',
 'tt7767422',
 'tt3107288',
 'tt8712204',
 'tt9264728',
 'tt3889642',
 'tt4122068',
 'tt12838766',
 'tt8134742',
 'tt6932244',
 'tt7587890',
 'tt13406094',
 'tt4635282',
 'tt0089562',
 'tt8595140',
 'tt15198608',
 'tt13024674',
 'tt10736580',
 'tt0384793',
 'tt3526078',
 'tt8633062',
 'tt9077562',
 'tt4052886',
 'tt13879466',
 'tt9561862',
 'tt3428912',
 'tt0058529',
 'tt2716382',
 'tt8425532',
 'tt8289480',
 'tt8787802',
 'tt4192812',
 'tt8108198',
 'tt7991608',
 'tt6271042',
 'tt0036641',
 'tt5296406',
 'tt7781432',
 'tt3420504',
 'tt7917178',
 'tt9288692',
 'tt8111088',
 'tt10147644',
 'tt1212974',
 'tt10772662',
 'tt2234222',
 'tt0062861',
 'tt0076723',
 'tt3120280',
 'tt8461224',
 'tt4604612',
 'tt1355642',
 'tt0060728',
 'tt10280296',
 'tt7403736',
 'tt12383460',
 'tt9064858',
 'tt6994156',
 'tt0165623',
 'tt14167390',
 'tt5206260',
 'tt0152930',
 'tt6336356',
 'tt6905542',
 'tt0092548',
 'tt4254242',
 'tt10148174',
 'tt7462410',
 'tt8634332',
 'tt0105265',
 'tt0073820',
 'tt8758086',
 'tt8369840',
 'tt9894470',
 'tt1937149',
 'tt7008682',
 'tt6803212',
 'tt5639976',
 'tt7167602',
 'tt9184982',
 'tt5096470',
 'tt7979142',
 'tt5598292',
 'tt1431115',
 'tt2140571',
 'tt7736496',
 'tt2442560',
 'tt0023940',
 'tt6712390',
 'tt8328716',
 'tt4765284',
 'tt11044858',
 'tt7167630',
 'tt7255502',
 'tt0465940',
 'tt4955642',
 'tt10763820',
 'tt9335498',
 'tt0089601',
 'tt0332047',
 'tt10521092',
 'tt4769836',
 'tt12298506',
 'tt5913798',
 'tt0093608',
 'tt8778064',
 'tt0275947',
 'tt11612120',
 'tt6519410',
 'tt5074352',
 'tt0096251',
 'tt4124758',
 'tt9812474',
 'tt8752440',
 'tt9775360',
 'tt0102768',
 'tt2296777',
 'tt0065225',
 'tt8239946',
 'tt0416496',
 'tt0045125',
 'tt0369179',
 'tt4857264',
 'tt5164196',
 'tt5144174',
 'tt9054192',
 'tt0107692',
 'tt8134186',
 'tt0974583',
 'tt3647998',
 'tt2452150',
 'tt2402207',
 'tt10886166',
 'tt6535880',
 'tt3895150',
 'tt0089461',
 'tt4600952',
 'tt7550000',
 'tt7510346',
 'tt9620288',
 'tt11125620',
 'tt8829830',
 'tt2879552',
 'tt0203425',
 'tt0058265',
 'tt0080040',
 'tt8150814',
 'tt7608028',
 'tt11639414',
 'tt0064100',
 'tt6257970',
 'tt13651632',
 'tt9110170',
 'tt8826128',
 'tt4477976',
 'tt6610158',
 'tt0062380',
 'tt0082288',
 'tt0040974',
 'tt6226232',
 'tt0259153',
 'tt6269368',
 'tt8236556',
 'tt1552211',
 'tt2076298',
 'tt2085059',
 'tt10155688',
 'tt2654620',
 'tt6513656',
 'tt0068421',
 'tt11388406',
 'tt9529546',
 'tt4354880',
 'tt10600398',
 'tt0060980',
 'tt6110648',
 'tt2802850',
 'tt10313066',
 'tt9738716',
 'tt4136456',
 'tt5936448',
 'tt5628902',
 'tt10919420',
 'tt0094961',
 'tt0112159',
 'tt0102744',
 'tt4106514',
 'tt3551096',
 'tt10009030',
 'tt0800325',
 'tt10327252',
 'tt0118460',
 'tt1074206',
 'tt9608818',
 'tt11908982',
 'tt2338151',
 'tt2235759',
 'tt1147687',
 'tt7049682',
 'tt3095734',
 'tt0115986',
 'tt10962368',
 'tt0102004',
 'tt0384642',
 'tt2560140',
 'tt4378376',
 'tt10308928',
 'tt0460780',
 'tt0084090',
 'tt2098220',
 'tt0044517',
 'tt8634202',
 'tt0068687',
 'tt12731980',
 'tt11032374',
 'tt0063991',
 'tt0089652',
 'tt0080365',
 'tt2313197',
 'tt9130508',
 'tt4998212',
 'tt5294518',
 'tt0042644',
 'tt0069427',
 'tt0097179',
 'tt4370528',
 'tt6475714',
 'tt9032400',
 'tt0068718',
 'tt0079117',
 'tt11804152',
 'tt0216651',
 'tt8910922',
 'tt0115491',
 'tt0070903',
 'tt8574252',
 'tt5715066',
 'tt5368542',
 'tt6802400',
 'tt8722888',
 'tt0072869',
 'tt7549892',
 'tt9077530',
 'tt4532368',
 'tt6905686',
 'tt10262380',
 'tt8664988',
 'tt1475582',
 'tt2017561',
 'tt6301452',
 'tt10332508',
 'tt6315640',
 'tt4815122',
 'tt5097410',
 'tt0240684',
 'tt0089731',
 'tt5323662',
 'tt9073958',
 'tt6372694',
 'tt6932874',
 'tt13138834',
 'tt1846442',
 'tt14324650',
 'tt9883996',
 'tt1918734',
 'tt0100107',
 'tt0113117',
 'tt0100994',
 'tt9580138',
 'tt8806524',
 'tt3501584',
 'tt8068860',
 'tt1032815',
 'tt0092746',
 'tt0119484',
 'tt0099026',
 'tt5198068',
 'tt0095583',
 'tt2974918',
 'tt8322060',
 'tt4669296',
 'tt12749596',
 'tt7221388',
 'tt2632424',
 'tt12971924',
 'tt9013182',
 'tt11024272',
 'tt0095776',
 'tt0106673',
 'tt13109952',
 'tt4154858',
 'tt2618986',
 'tt0068359',
 'tt5711280',
 'tt0086491',
 'tt11240506',
 'tt6259380',
 'tt13056008',
 'tt1865718',
 'tt0084472',
 'tt11762434',
 'tt8980602',
 'tt1893273',
 'tt7423538',
 'tt4823776',
 'tt1830643',
 'tt11681250',
 'tt1545304',
 'tt0098097',
 'tt4590256',
 'tt13429362',
 'tt1950235',
 'tt4348012',
 'tt7646322',
 'tt8685324',
 'tt0060550',
 'tt12451520',
 'tt0070016',
 'tt9898858',
 'tt6908274',
 'tt10691162',
 'tt2397461',
 'tt0108147',
 'tt0884224',
 'tt2431438',
 'tt9348692',
 'tt6763664',
 'tt9866072',
 'tt5865326',
 'tt0054469',
 'tt10826054',
 'tt3658772',
 'tt0054428',
 'tt2718440',
 'tt0099141',
 'tt0075809',
 'tt3472226',
 'tt0443295',
 'tt12676326',
 'tt2364582',
 'tt8593252',
 'tt5675620',
 'tt2850386',
 'tt0279967',
 'tt10048342',
 'tt3520702',
 'tt2699128',
 'tt6903284',
 'tt4217392',
 'tt5689068',
 'tt4332232',
 'tt2357547',
 'tt7057496',
 'tt7978672',
 'tt2091935',
 'tt0104040',
 'tt1898069',
 'tt2166834',
 'tt3152592',
 'tt5691552',
 'tt10314450',
 'tt0052993',
 'tt0308152',
 'tt8740790',
 'tt2372162',
 'tt10060094',
 'tt9140560',
 'tt1586680',
 'tt10919486',
 'tt2771780',
 'tt9203694',
 'tt0109190',
 'tt0101775',
 'tt11102190',
 'tt13173144',
 'tt6269192',
 'tt0264508',
 'tt0487831',
 'tt11188624',
 'tt4799066',
 'tt7737640',
 'tt0098412',
 'tt8228288',
 'tt0093148',
 'tt1124373',
 'tt5862312',
 'tt10314462',
 'tt0094025',
 'tt8404256',
 'tt0060782',
 'tt1883367',
 'tt1486217',
 'tt5614844',
 'tt0469021',
 'tt0369226',
 'tt7914416',
 'tt4016454',
 'tt2231874',
 'tt8686106',
 'tt10065694',
 'tt5989218',
 'tt0107091',
 'tt8324422',
 'tt7178640',
 'tt9059760',
 'tt11140488',
 'tt4230076',
 'tt0082951',
 'tt13269536',
 'tt0089730',
 'tt4267026',
 'tt0102915',
 'tt2575988',
 'tt4180514',
 'tt8741290',
 'tt0081793',
 'tt10062652',
 'tt6521876',
 'tt5516154',
 'tt11576124',
 'tt13061914',
 'tt1489428',
 'tt5420210',
 'tt11815960',
 'tt5057054',
 'tt7589524',
 'tt9026184',
 'tt10361016',
 'tt7374948',
 'tt12829958',
 'tt9308382',
 'tt0082509',
 'tt6473344',
 'tt8694364',
 'tt6977338',
 'tt0095889',
 'tt0810788',
 'tt5476182',
 'tt1693592',
 'tt4504044',
 'tt9208876',
 'tt9741310',
 'tt0124901',
 'tt0085936',
 'tt0070825',
 'tt12809988',
 'tt1196948',
 'tt0375568',
 'tt11235772',
 'tt2359704',
 'tt12528166',
 'tt1999995',
 'tt2071645',
 'tt2628232',
 'tt6920084',
 'tt0039515',
 'tt8110640',
 'tt0243655',
 'tt7984766',
 'tt2027136',
 'tt3322314',
 'tt8361028',
 'tt0077533',
 'tt10888878',
 'tt9140342',
 'tt4009278',
 'tt5085924',
 'tt0417299',
 'tt8110232',
 'tt5640450',
 'tt5664636',
 'tt10229558',
 'tt0079336',
 'tt0080436',
 'tt2072230',
 'tt9373688',
 'tt7153488',
 'tt5113040',
 'tt7038606',
 'tt8134470',
 'tt1073498',
 'tt1525366',
 'tt1213644',
 'tt12137964',
 'tt0100477',
 'tt0029284',
 'tt8762206',
 'tt8231668',
 'tt0068617',
 'tt5304992',
 'tt9354944',
 'tt2433738',
 'tt5624466',
 'tt0100135',
 'tt0082592',
 'tt6658720',
 'tt0046183',
 'tt3714720',
 'tt13804084',
 'tt3920596',
 'tt10418662',
 'tt2243973',
 'tt0093171',
 'tt0994314',
 'tt0086618',
 'tt8160834',
 'tt0081112',
 'tt0802948',
 'tt3111426',
 'tt10618286',
 'tt2205697',
 'tt0080646',
 'tt1986770',
 'tt7043012',
 'tt1500491',
 'tt0088961',
 'tt0092860',
 'tt0086525',
 'tt0460649',
 'tt7826376',
 'tt8485364',
 'tt11640020',
 'tt0421994',
 'tt0100212',
 'tt3322312',
 'tt1495708',
 'tt7817340',
 'tt4876134',
 'tt11196036',
 'tt13318052',
 'tt0131857',
 'tt4176826',
 'tt8004664',
 'tt9115530',
 'tt7937254',
 'tt0117110',
 'tt8235236',
 'tt1836037',
 'tt3672742',
 'tt7235466',
 'tt2191671',
 'tt7801964',
 'tt0064622',
 'tt0062657',
 'tt0058230',
 'tt1046163',
 'tt9314984',
 'tt1153706',
 'tt4687882',
 'tt3286052',
 'tt0062873',
 'tt5439812',
 'tt0060548',
 'tt8745960',
 'tt4667888',
 'tt0120770',
 'tt10329614',
 'tt0424774',
 'tt0400717',
 'tt0065988',
 'tt2140203',
 'tt11192306',
 'tt5912064',
 'tt11456054',
 'tt1241317',
 'tt11274100',
 'tt5827228',
 'tt2583620',
 'tt1910272',
 'tt0054127',
 'tt1327788',
 'tt8435002',
 'tt13446168',
 'tt0119013',
 'tt7421814',
 'tt0119707',
 'tt0123948',
 'tt2756032',
 'tt7939766',
 'tt0082242',
 'tt0384286',
 'tt4975856',
 'tt10451852',
 'tt11263022',
 'tt0058092',
 'tt5734576',
 'tt2112124',
 'tt7946422',
 'tt5014882',
 'tt10345008',
 'tt4126476',
 'tt9784456',
 'tt0084237',
 'tt8707922',
 'tt0257568',
 'tt0143808',
 'tt1638002',
 'tt7608418',
 'tt0467110',
 'tt8075496',
 'tt3877200',
 'tt1972779',
 'tt4145384',
 'tt10121392',
 'tt0430105',
 'tt1441951',
 'tt0080907',
 'tt0041594',
 'tt1888075',
 'tt1800246',
 'tt5607976',
 'tt10083640',
 'tt0111756',
 'tt0804492',
 'tt3131456',
 'tt3774694',
 'tt0492044',
 'tt7945720',
 'tt0449487',
 'tt0078721',
 'tt1187043',
 'tt0058536',
 'tt8860450',
 'tt0078504',
 'tt7971476',
 'tt3205802',
 'tt0112453',
 'tt0113820',
 'tt0082406',
 'tt10574558',
 'tt8376234',
 'tt11285548',
 'tt9698442',
 'tt0109402',
 'tt3661394',
 'tt1114677',
 'tt0372237',
 'tt8001226',
 'tt3636060',
 'tt0318403',
 'tt9354842',
 'tt0081534',
 'tt0790604',
 'tt0077696',
 'tt1800302',
 'tt6095472',
 'tt12822926',
 'tt13097858',
 'tt11640018',
 'tt1361336',
 'tt4270492',
 'tt0107985',
 'tt13320784',
 'tt7520794',
 'tt6185074',
 'tt3440298',
 'tt3846674',
 'tt7547410',
 'tt7660970',
 'tt8510488',
 'tt4063800',
 'tt0405325',
 'tt1408253',
 'tt0472954',
 'tt0119310',
 'tt5994364',
 'tt4158110',
 'tt2261287',
 'tt0328832',
 'tt4779326',
 'tt2580382',
 'tt0286788',
 'tt0087597',
 'tt0098966',
 'tt0117918',
 ...]

In [34]:
len(movie_ids)

9370

In [35]:
movie_ids_df = pd.DataFrame(columns=['movie id'])
movie_ids_df['movie id'] = movie_ids
movie_ids_df

        movie id
0      tt1837492
1     tt12361178
2     tt10752004
3      tt1190634
4      tt9544034
...          ...
9365  tt12545180
9366   tt6337766
9367   tt7350790
9368   tt0111948
9369   tt8045690

[9370 rows x 1 columns]

In [36]:
merged_movie_ids_and_ratings = pd.merge(movie_ids_df, remaining_ratings_df, how='inner', left_on='movie id', right_on='movie id')
merged_movie_ids_and_ratings

,movie id,user id,rating,content,date
0,tt1837492,ur51094543,3,Started off great but then had its ups and dow...,2 January 2018
1,tt1837492,ur22484170,5,This controversial and well made series is bou...,21 July 2017
2,tt1837492,ur18044142,2,"Positives: \n1. Addresses, mostly from a teen ...",5 May 2018
3,tt1837492,ur18044142,2,"Positives:\n1. Addresses, mostly from a teen p...",18 May 2018
4,tt1837492,ur18044142,2,Just as some (many?) lawyers are ambulance cha...,21 June 2019
...,...,...,...,...,...
101216,tt12545180,ur47115801,5,I couldnt turn away it was so awful it was gre...,25 November 2021
101217,tt6337766,ur71305899,1,Puppets are a thing of the past and that is ve...,28 August 2021
101218,tt7350790,ur29911262,3,I was surprised to read a review which demonis...,5 November 2017
101219,tt0111948,ur71305899,4,Despite it having a worthless mutt I must say ...,24 November 2021
101220,tt8045690,ur59148101,3,Luis Miguel is arguably one of the most famous...,24 April 2018

In [37]:
movies = pd.read_csv('../data/datasets/movie/cleaned_1_detail.csv', sep=',', encoding='latin-1')

In [38]:
movies.head()

,movie id,title,series,release year,certification,duration,average rating,rating total,genre list,content,countries of origin,official sites,languages,production companies,budget
0,tt0102813,Rover Dangerfield,NaN,1991,G,1h 14m,6.0,3K,Animation|Comedy|Family,A Vegas show dog gets ditched in the sticks an...,United States,NaN,English,NaN,NaN
1,tt1086761,Keeping Up with the Kardashians,TV Series,2006Ã¢Â€Â“2021,TV-14,44m,2.8,29K,Drama|Family|Reality-TV,A peek inside the exploits and privileged priv...,United States,Official sites|Official Facebook|Official Inst...,English|Spanish,NaN,NaN
2,tt0075686,Annie Hall,NaN,1977,PG,1h 33m,8.0,259K,Comedy|Romance,"Alvy Singer, a divorced Jewish comedian, refle...",United States,NaN,English|German,NaN,"$38,287,178"
3,tt1402488,Happy Feet Two,NaN,2011,PG,1h 40m,5.9,44K,Animation|Adventure|Comedy,"Mumble's son, Erik, is struggling to realize h...",Australia|United States|Antarctica|New Zealand,Official site,English,NaN,"$159,197,038"
4,tt15523186,Warning,NaN,2021,NaN,NaN,9.6,310,Action,"Set in India, Action Movie Warning is about th...",India,NaN,Punjabi,NaN,NaN

In [39]:
remaining_ids = merged_movie_ids_and_ratings['movie id'].value_counts().index.tolist()
remaining_id_df = pd.DataFrame(columns=['movie id'])
remaining_id_df['movie id'] = remaining_ids
remaining_id_df.to_csv('../data/datasets/movie/remaining_ids.csv', sep=',', encoding='latin-1', index=False)

In [40]:
df = pd.merge(movies, remaining_id_df, how='inner', on='movie id')
df.head(5)

,movie id,title,series,release year,certification,duration,average rating,rating total,genre list,content,countries of origin,official sites,languages,production companies,budget
0,tt0102813,Rover Dangerfield,NaN,1991,G,1h 14m,6.0,3K,Animation|Comedy|Family,A Vegas show dog gets ditched in the sticks an...,United States,NaN,English,NaN,NaN
1,tt1086761,Keeping Up with the Kardashians,TV Series,2006Ã¢Â€Â“2021,TV-14,44m,2.8,29K,Drama|Family|Reality-TV,A peek inside the exploits and privileged priv...,United States,Official sites|Official Facebook|Official Inst...,English|Spanish,NaN,NaN
2,tt0075686,Annie Hall,NaN,1977,PG,1h 33m,8.0,259K,Comedy|Romance,"Alvy Singer, a divorced Jewish comedian, refle...",United States,NaN,English|German,NaN,"$38,287,178"
3,tt1402488,Happy Feet Two,NaN,2011,PG,1h 40m,5.9,44K,Animation|Adventure|Comedy,"Mumble's son, Erik, is struggling to realize h...",Australia|United States|Antarctica|New Zealand,Official site,English,NaN,"$159,197,038"
4,tt1087461,Megan Is Missing,NaN,2011,Not Rated,1h 25m,4.5,12K,Drama|Horror|Thriller,Two teenage girls encounter an Internet child ...,United States,MySpace|Official site,English,NaN,NaN

In [41]:
df.to_csv('../data/datasets/movie/remaining_detail.csv', sep=',', encoding='latin-1', index=False)

In [42]:
movie_ids = df['movie id']
movie_id_df = pd.DataFrame(columns=['movie id'])
movie_id_df['movie id'] = movie_ids
df = pd.merge(movie_id_df, merged_movie_ids_and_ratings, how='inner', on='movie id')

In [43]:
df.head()

,movie id,user id,rating,content,date
0,tt0102813,ur0391152,2,I've always had kind of a perverse curiosity a...,22 August 2010
1,tt0102813,ur34049683,3,Everything about this movie is from the mind o...,14 March 2013
2,tt0102813,ur23566468,3,Rover Dangerfield is loosely based on the late...,20 April 2020
3,tt0102813,ur4195782,2,I started out this movie with a positive attit...,8 August 2008
4,tt0102813,ur1657894,3,'Rover Dangerfield' is the animated story of d...,28 March 2006

In [44]:
df.to_csv('../data/datasets/rating/remaining_detail.csv', sep=',', encoding='latin-1', index=False)